[package]
name = "opal-cli"
version = "0.1.0"
authors = ["Andrew Vy <andrew@andrewvy.com>"]

[dependencies]
clap = "2.26.0"
grpc = "0.*"
protobuf = "1.*"
futures = "0.1"
futures-cpupool = "0.1"
tls-api = "0.1.10"
tls-api-openssl = "0.1.10"
